### ISSUE TITLE
model_api_key: expected one argument

### ISSUE THREAD

**Issue by chohanwu** [googleforgames/clean-chat#8]
I ran the "make deploy-scoring-engine-interactive" step and have entered all the environment variable in my environment.
However, I see an error asking for my api key, even thought my api key was presented.

This is the error I see:

usage: main.py [-h] --gcp_project GCP_PROJECT --region REGION --job_name
               JOB_NAME --gcp_staging_location GCP_STAGING_LOCATION
               --gcp_tmp_location GCP_TMP_LOCATION --batch_size BATCH_SIZE
               --pubsub_topic_text_input PUBSUB_TOPIC_TEXT_INPUT
               --pubsub_topic_text_scored PUBSUB_TOPIC_TEXT_SCORED
               --pubsub_topic_toxic PUBSUB_TOPIC_TOXIC --bq_dataset_name
               BQ_DATASET_NAME --bq_table_name BQ_TABLE_NAME
               --window_duration_seconds WINDOW_DURATION_SECONDS
               --window_sliding_seconds WINDOW_SLIDING_SECONDS --runner RUNNER
               --extra_package EXTRA_PACKAGE --toxic_user_threshold
               TOXIC_USER_THRESHOLD [--model_api_key MODEL_API_KEY]
main.py: error: argument --model_api_key: expected one argument
make: *** [Makefile:84: deploy-scoring-engine-interactive] Error 2

Any insight would be helpful. Thanks!

**Comment by zaratsian** [comment]
Hi @chohanwu, does your config have a variable called "TF_VAR_MODEL_API_KEY" that points to your API key?

If you check out this part of the config file (https://github.com/googleforgames/clean-chat/blob/master/config.default#L55), you'll notice that you need to set an environment variable called "TF_VAR_MODEL_API_KEY".

**Comment by chohanwu** [comment]
Thanks @zaratsian! 
Yes, I set my Cohere API key in the environment variable
<img width="1592" alt="Screen Shot 2022-06-07 at 3 45 42 PM" src="https://user-images.githubusercontent.com/64520338/172469156-f5540f98-7a1d-4f10-98c7-5fe3ce0b86ce.png">
e

**Comment by zaratsian** [comment]
Hi @chohanwu, in the setup instructions, step #2 is where you'll execute this command (cp config.default config), then edit the config file to set your variable, such as your API key. 

Here's a link to the setup instructions: https://github.com/googleforgames/clean-chat

Search for "Make a copy of the config.default" and that will take you to the appropriate part within the setup instructions. 

Let me know if you need any additional help with the deployment. I'm going to close this issue now, but please open up another one if your run into an issue.
